from __future__ import annotations

from typing import Any, AsyncIterator, Protocol, runtime_checkable


class CameraPort(Protocol):
    def open(self) -> None: ...
    def capture(self, window_ms: int) -> dict[str, object]: ...
    def close(self) -> None: ...


class AudioPort(Protocol):
    def play_text(self, text: str, voice_id: str | None = None) -> None: ...


class GPIOPort(Protocol):
    def set_led(self, color: str, pattern: str) -> None: ...


class TransportPort(Protocol):
    async def send_event(self, event: dict[str, Any]) -> None: ...


@runtime_checkable
class SessionTransportPort(TransportPort, Protocol):
    async def connect(self) -> None: ...
    def commands(self) -> AsyncIterator[dict[str, Any]]: ...
    async def close(self) -> None: ...
